### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bkresning** [virocon-organization/viroconcom#41] opened 2019-12-12 18:05 UTC
I experienced an error at the installation. I am using anaconda spyder in windows.

pip install viroconcom was done successfully but the toolbox does not work propperly. **In brief, IFORM contour method works but the HDC method does not.**

I re-installed the toolbox but interestingly it does not listed (>> conda list). Does anyone know how to resolve this issue? Screenshots of errors are pasted below.

![image(2)](https://user-images.githubusercontent.com/58825004/70737205-0035cf80-1ce0-11ea-97d7-8c79c73fe7f7.png)

![image(3)](https://user-images.githubusercontent.com/58825004/70737202-0035cf80-1ce0-11ea-8b6f-5f0272fc972c.png)
![image](https://user-images.githubusercontent.com/58825004/70737203-0035cf80-1ce0-11ea-9859-89aca957fc4c.png)
![image(1)](https://user-images.githubusercontent.com/58825004/70737204-0035cf80-1ce0-11ea-9e9b-0065f7f3dc03.png)

**Comment by bkresning** [comment] 2019-12-12 18:53
Temporary solution:

I downgraded my numpy to version 1.14.2 and the code works fine now.

**Comment by ahaselsteiner** [comment] 2019-12-13 14:48
Thanks @bkresning for reporting this problem in an issue and great that you already found a temporary solution that works for you. Possibly the problem is that the newer numpy version does not work with the depreciated 'dims' keyword. I will try to solve the issue.

**Comment by bkresning** [comment] 2019-12-13 17:09
@ahaselsteiner 

I found an interesting thing with the code under the latest version of numpy. I played around with the limit of HDC method (calculate_contours_similar_to_docs.py). It gives me results when I decrease the computational limit (results looks like a box due - error in calculation). However, when I change the number back to example given or larger the code produces nothing.

**Comment by ahaselsteiner** [comment] 2019-12-16 19:40
Fixed the problem. I just updated the requirement to numpy==1.17.4 and adjusted the code to be compatible with it.  You can download this new version (1.2.1) from GitHub, I have not uploaded it to PyPI yet.

@bkresning So after your temporarily solution you still had problems?
Does the problem remain with version 1.2.1?

**Comment by bkresning** [comment] 2019-12-17 17:11
@ahaselsteiner Hi, thank you for the update. I installed viroconcom v1.2.3 and it works smoothly with anaconda3 + spyder 3.7 (numpy 1.16.5)

**Comment by ahaselsteiner** [comment] 2019-12-17 17:14
@bkresning Great, glad to hear that. Then I close this issue as we solved the problem.

**Closed by ahaselsteiner** 2019-12-17 17:14 UTC
Labels: bug
