### ISSUE TITLE
Parameter out of bounds

### ISSUE THREAD

**Issue by huyquangt** [virocon-organization/viroconcom#37] opened 2019-02-23 04:38 UTC
Hi,

I got an error message as below. Do you know why? Thanks! : 

iform_contour_30 = IFormContour(my_fit.mul_var_dist, return_period_30, 1, 100)

  File "C:\Python3\lib\site-packages\viroconcom\contours.py", line 139, in __init__
    super().__init__(mul_var_distribution, return_period, state_duration, timeout, n_points)

  File "C:\Python3\lib\site-packages\viroconcom\contours.py", line 71, in __init__
    computed = self._setup(*args, **kwargs)

  File "C:\Python3\lib\site-packages\viroconcom\contours.py", line 183, in _setup
    dependencies=self.distribution.dependencies[index])

  File "C:\Python3\lib\site-packages\viroconcom\distributions.py", line 184, in i_cdf
    shape_val, loc_val, scale_val = self._get_parameter_values(rv_values, dependencies)

  File "C:\Python3\lib\site-packages\viroconcom\distributions.py", line 223, in _get_parameter_values
    self._check_parameter_value(i, value)

  File "C:\Python3\lib\site-packages\viroconcom\distributions.py", line 261, in _check_parameter_value
    "".format(param_name, valid["min"], param_value))

ValueError: Parameter out of bounds. shape has to be strictly greater than 0, but was nan

**Comment by ahaselsteiner** [comment] 2019-02-23 06:58
Hi Huy Quang Tran,

thanks for opening an issue.

It seems to be an issue with the fitted distribution, but based on the single code line I cannot tell.

Could you post your complete python file that I can reproduce the error?

Best, Andreas

**Comment by huyquangt** [comment] 2019-02-24 01:38
Hi ahaselsteiner,

I found the problem. It was due to using the following description for Tz in my data:

dist_description_tz = {'name': 'Lognormal_SigmaMu','dependency': (0,  None, 0), 'functions': ('exp3', None, 'power3')};

When I replaced this line by:

dist_description_tz  = {'name': 'Lognormal', 'dependency': (None, None, 0), 'functions': (None, None, 'exp3')}

It worked!  but fitting is not good like attached. How come? 

Thanks! 
Huy
![fit_tz](https://user-images.githubusercontent.com/32722297/53293903-e995b900-3830-11e9-8cca-6d06a3f801c2.png)

**Comment by ahaselsteiner** [comment] 2019-02-26 07:39
Hi Huy,

you can use viroconcom with any dataset. I agree that in your case the selected model structure does not fit the dataset well. That often happens with parametric models. I don't know about your dataset and don't have a specific model structure I can recommend you.

As a baseline you might try the model structure recommended in DNVGL-RP-C205. I recently fitted it to three three different datasets. You can find the open source code here and reproduce the model fit and contour computation: https://github.com/ec-benchmark-organizers/ec-benchmark/blob/master/organizers-code/compute_baseline_contour_dataset_a_to_c.py 

Best, Andreas

**Comment by huyquangt** [comment] 2019-03-04 08:43
Dear Andreas,

Thank you for directing me to   compute_baseline_contour_dataset_a_to_c.py script, the error message still exists there with my dataset that I attached here.

Could you please help find out what could be the cause of it?

Thanks in advance!

Best, Huy
[MYDATA.txt](https://github.com/virocon-organization/viroconcom/files/2924904/MYDATA.txt)

**Comment by ahaselsteiner** [comment] 2019-03-04 13:23
Thanks for posting your dataset. Could you please also post the python script that (together with the dataset) leads to the error that you describe such that I can reproduce it?

**Comment by huyquangt** [comment] 2019-03-05 07:47
Dear Andreas,

The code I used is below. Basically, I use  example_compute_contour_dataset_a_to_c.py script in ec-benchmark-master\organizers-code as my data format is similar to those in ec-benchmark-master\datasets.

Thanks for help,

Huy

`import numpy as np
import matplotlib.pyplot as plt

from viroconcom.fitting import Fit
from viroconcom.contours import IFormContour
from plot import plot_contour
from contour_statistics import points_outside
from read_write import read_dataset, determine_file_name, write_contour, read_contour

# Read dataset A, B  or C.
DATASET_CHAR = 'MYDATA'
file_path =  DATASET_CHAR + '.txt'
sample_hs, sample_tz, label_hs, label_tz= read_dataset(file_path)

# Define the structure of the probabilistic model that will be fitted to the
# dataset. We will use the model that is recommended in DNV-RP-C205 (2010) on
# page 38 and that is called 'conditonal modeling approach' (CMA).
dist_description_hs = {'name': 'Weibull_3p',
                      'dependency': (None, None, None),
                      'width_of_intervals': 0.5}
dist_description_tz = {'name': 'Lognormal_SigmaMu',
                      'dependency': (0,  None, 0), #Shape, Location, Scale
                      'functions': ('exp3', None, 'power3') #Shape, Location, Scale
                      }

# Fit the model to the data.
my_fit = Fit((sample_hs, sample_tz), (
    dist_description_hs, dist_description_tz))
dist0 = my_fit.mul_var_dist.distributions[0]
print('First variable: ' + dist0.name + ' with '
      + ' scale: ' + str(dist0.scale) + ', '
      + ' shape: ' + str(dist0.shape) + ', '
      + ' location: ' + str(dist0.loc))
print('Second variable: ' + str(my_fit.mul_var_dist.distributions[1]))

# Compute a IFORM-contours with a return periods of 1 and 20 years.
return_period_1 = 1
iform_contour_1 = IFormContour(my_fit.mul_var_dist, return_period_1, 0.5, 100)
return_period_30 = 30
iform_contour_30 = IFormContour(my_fit.mul_var_dist, return_period_30, 0.5, 100)

# Save the contours as a csv files in the required format.
file_name_1 = determine_file_name('John', 'Doe', DATASET_CHAR, return_period_1)
write_contour(iform_contour_1.coordinates[0][0],
              iform_contour_1.coordinates[0][1],
              file_name_1,
              label_x=label_hs,
              label_y=label_tz)
file_name_30 = determine_file_name('John', 'Doe', DATASET_CHAR, return_period_30)
write_contour(iform_contour_30.coordinates[0][0],
              iform_contour_30.coordinates[0][1],
              file_name_30,
              label_x=label_hs,
              label_y=label_tz)
# Read the contours from the csv files.
(contour_hs_1, contour_tz_1) = read_contour(file_name_1)
(contour_hs_30, contour_tz_30) = read_contour(file_name_30)

# Find datapoints that exceed the 20-yr contour.
hs_outside, tz_outside, hs_inside, tz_inside = \
    points_outside(contour_hs_30,
                   contour_tz_30,
                   np.asarray(sample_hs),
                   np.asarray(sample_tz))
print('Number of points outside the contour: ' +  str(len(hs_outside)))

# Plot the contour.
fig = plt.figure(figsize=(5, 5), dpi=150)
ax = fig.add_subplot(111)
# Plot the 1-year contour.
plot_contour(x=contour_tz_1,
             y=contour_hs_1,
             return_period=return_period_1,
             ax=ax,
             x_label=label_tz,
             y_label=label_hs,
             line_style='b--')
# Plot the 20-year contour and the sample.
sample_struct = [np.asarray(sample_tz),
                 np.asarray(sample_hs),
                 tz_inside,
                 hs_inside,
                 tz_outside,
                 hs_outside,
                 return_period_30,
                 [False, False, False, False]]
plot_contour(x=contour_tz_30,
             y=contour_hs_30,
             return_period=return_period_30,
             ax=ax,
             x_label=label_tz,
             y_label=label_hs,
             line_style='b-',
             sample=sample_struct)
plt.title('Dataset ' + DATASET_CHAR)
plt.show()
`

**Comment by huyquangt** [comment] 2019-03-05 07:49
Dear Andreas,

The code I used is attached. . Basically, I use example_compute_contour_dataset_a_to_c.py script in ec-benchmark-master\organizers-code as my data format is similar to those in ec-benchmark-master\datasets.

Thanks for help,

Huy
[test_huy_data.txt](https://github.com/virocon-organization/viroconcom/files/2929807/test_huy_data.txt)

**Comment by ahaselsteiner** [comment] 2019-03-08 06:20
Hi Huy,

I could reproduce your error. The cause is that the best fitting 3-parameter Weibull distribution in your case has a location parameter that is negative. Consequently, in your joint distribution negative values for Hs occur. Then the parameters for Tz are computed based on negative Hs values and that leads to negative values for the Tz-distribution's scale parameter, which is not valid.

I was able to solve your problem by choosing a 2-parameter Weibull distribution instead of the 3-parameter Weibull distribution. This is the same as setting the location parameter of the 3-parameter Weibull distribution to zero. 

```
dist_description_hs = {'name': 'Weibull_2p',
                      'dependency': (None, None, None),
                      'width_of_intervals': 0.5}
dist_description_tz = {'name': 'Lognormal_SigmaMu',
                      'dependency': (0,  None, 0), #Shape, Location, Scale
                      'functions': ('exp3', None, 'power3') #Shape, Location, Scale
                      }
```


Below are plots of the fit's dependence functions and of the computed environmental contours. Attached is also the code I used such that you can reproduce it.

The root cause of the problem is that we allow the 3-parameter Weibulldistribution to have negative values for the location parameter. I have to think if we should change that.

Let me know if using the 2-parameter Weibull distribution solved the issue for you.

Best,
Andreas

![issue37-dependence-functions](https://user-images.githubusercontent.com/11452055/54011297-f27d7780-41ac-11e9-9094-2346b5cff357.png)
![issue37-contours](https://user-images.githubusercontent.com/11452055/54011302-f7dac200-41ac-11e9-82fb-1a1c290366d0.png)
[issue37-organizers-code-repo.zip](https://github.com/virocon-organization/viroconcom/files/2944582/issue37-organizers-code-repo.zip)

**Comment by huyquangt** [comment] 2019-03-10 06:28
Thank you Andreas a lot. I have also tested my data with 2-parameters distribution. It works too. However,  as you can see there is a huge difference  between contour 1 and 30-year contour lines in the upper part where 30-year contour line for Tz can be up to 70 second. Does it make sense?  Noted that this data comes from a spectral wave model extracted at the location nearby the coasts.

Thank you again & have a great weekend!
Huy

**Comment by ahaselsteiner** [comment] 2019-03-11 04:09
Huy, good to hear that it works with your dataset too. Unfortunately, I cannot judge to which degree the contour's high Tz-values makes sense. Certainly they strongly exceed the maximum values in your dataset.

**Comment by huyquangt** [comment] 2019-03-11 06:06
thank you very much Andreas!

**Comment by ahaselsteiner** [comment] 2020-01-22 18:48
@huyquangt I decided to change the code such that negative location parameters are not allowed for the translated Weibull distribution. For variables that are relevant for environmental contours (wave height, wind speed, current speed), negative values don't make sense, they would be unphysical. In the new version if the maximum likelihood estimation leads to loc < 0, loc is set to 0.

The change is now in the master branch and will be in the next version of viroconcom (1.2.13).

**Closed** 2020-07-01 14:10 UTC
Labels: bug
